{{- if .Values.stanbox.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name:  {{ template "stan.name" . }}-box
  labels:
    app: {{ template "stan.name" . }}-box
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  containers:
  - name: nats-box
    image: {{ .Values.stanbox.image }}
    imagePullPolicy: {{ .Values.stanbox.pullPolicy }}
    env:
    - name: NATS_URL
      value: {{ .Values.stan.nats.url }}
    - name: STAN_CLUSTER
      value: {{ template "stan.name" . }}
    command:
     - "tail"
     - "-f"
     - "/dev/null"
{{- end }}
