##################################
#                                #
#  NATS Streaming Configuration  #
#                                #
##################################
stan:
  image: nats-streaming:0.17.0
  pullPolicy: IfNotPresent

  # Cluster name, generated into a name from the
  # release name by default.
  clusterID: 

  logging:
    debug: 
    trace: 

  # In case of NATS not being embedded then
  # an URL for NATS is required.
  nats:
    url:

###########################
#                         #
#  Storage configuration  #
#                         #
###########################
store:
  # One value possible out of: "file" | "sql" | "memory"
  type: file

  # In case of using file or sql storage, sets up a 3 node cluster.
  cluster:
    enabled: false

  # 
  # Fault tolerance group
  # 
  ft:
    group:

  # Configures streaming/store_limits as is.
  # 
  # NOTE: Section in snake case since they will become
  # the same objects.
  # 
  # Look at the NATS Streaming configuration for this.
  # 
  limits:

  # 
  # Memory storage settings.
  # TODO: support setting limits resources.
  memory: 

  # 
  # File storage settings.
  # 
  file:
    path: /data/stan/store
    storageSize: 1Gi

  # 
  # SQL storage settings
  # 
  sql:
    driver: postgres

    # TODO: Use secret reference and include instead for the password.
    # 
    # e.g.
    # source: "dbname=postgres user=postgres password=stan host=stan-db sslmode=disable"
    # 
    source: ""

    # Initialize the database.
    initdb:
      enabled: false

      # Client to use to init the db.
      image: postgres:11

    dbName: postgres
    dbUser: postgres
    dbPassword: stan
    dbHost: ""
    dbPort: 5432

# 
# 
# NATS Box
# 
# https://github.com/nats-io/nats-box
# 
natsbox:
  enabled: true
  image: synadia/nats-box:0.3.0
  pullPolicy: IfNotPresent

#######################################
#                                     #
# Prometheus Exporter configuration   #
#                                     #
#######################################
exporter:
  image: synadia/prometheus-nats-exporter:0.6.0
  pullPolicy: IfNotPresent

##################################
#                                #
#  Embedded NATS Configuration   #
#                                #
##################################
# TODO: Support NATS embedded mode by including
# nats chart values.
