---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    prometheus: nats-surveyor
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
---
# Service used by Grafana as a datasource
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    prometheus: nats-surveyor
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-surveyor-grafana
  labels:
    app: nats-surveyor-grafana
spec:
  selector:
    matchLabels:
      app: nats-surveyor-grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-surveyor-grafana
    spec:
      containers:
      - name: nats-surveyor-grafana
        image: csullivan9999/nats-surveyor-grafana
        ports:
        - containerPort: 3000
          name: web

        # Disable all cpu limits for the server.
        #
        resources:
          requests:
            cpu: 0
