---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: nats-prometheus
spec:
  scrapeInterval: "5s"
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: nats
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  endpoints:
  - port: metrics
