---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: nats-surveyor-grafana
  ports:
  - name: web
    # nodePort: 30300
    port: 3000
    protocol: TCP
    targetPort: web
---
# Service used by Grafana as a datasource
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    prometheus: nats-surveyor
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-surveyor-grafana
  labels:
    app: nats-surveyor-grafana
spec:
  selector:
    matchLabels:
      app: nats-surveyor-grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-surveyor-grafana
    spec:
      containers:
      - name: nats-surveyor-grafana
        image: synadia/nats-surveyor-grafana:0.0.1-alpha1
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"

        ports:
        - containerPort: 3000
          name: wep

        # Disable all cpu limits for the server.
        #
        resources:
          requests:
            cpu: 0
